#!/bin/bash

echo "🧹 DNS 清理指南 - Cloudflare Pages"
echo "================================="
echo ""
echo "📋 请在 Cloudflare DNS 设置中执行以下操作："
echo ""
echo "1️⃣ 删除以下 A 记录："
echo "   ❌ 185.199.108.153"
echo "   ❌ 185.199.109.153"
echo "   ❌ 185.199.110.153"
echo "   ❌ 185.199.111.153"
echo ""
echo "2️⃣ 保留或更新 CNAME 记录："
echo "   如果 Cloudflare Pages 自动添加了新记录，旧的会被替换"
echo ""
echo "3️⃣ 最终 DNS 配置应该是："
echo "   CNAME @ → ai-bubblebrain-daily-news.pages.dev (或 Cloudflare 自动设置的值)"
echo "   CNAME www → bubblenews.today"
echo ""
echo "⚠️  重要：添加自定义域名后，Cloudflare Pages 会自动处理 DNS！"
echo ""
echo "📍 当前 Pages URL："
echo "   https://ai-bubblebrain-daily-news.pages.dev"
echo "   https://df4fd1ae.ai-bubblebrain-daily-news.pages.dev"
echo ""
echo "🎯 添加域名后将可访问："
echo "   https://bubblenews.today"
echo "   https://www.bubblenews.today"