#!/bin/bash

echo "🔧 DNS 配置修复指南"
echo "===================="
echo ""
echo "请在 Cloudflare Dashboard 中进行以下操作："
echo ""
echo "1️⃣ 删除现有的错误 A 记录"
echo "   当前错误的记录："
echo "   - 104.21.92.254"
echo "   - 172.67.201.185"
echo ""
echo "2️⃣ 添加正确的 GitHub Pages A 记录："
echo ""
echo "┌──────┬──────┬─────────────────┬──────────┬──────┐"
echo "│ Type │ Name │ Content         │ Proxy    │ TTL  │"
echo "├──────┼──────┼─────────────────┼──────────┼──────┤"
echo "│ A    │ @    │ 185.199.108.153 │ Proxied  │ Auto │"
echo "│ A    │ @    │ 185.199.109.153 │ Proxied  │ Auto │"
echo "│ A    │ @    │ 185.199.110.153 │ Proxied  │ Auto │"
echo "│ A    │ @    │ 185.199.111.153 │ Proxied  │ Auto │"
echo "└──────┴──────┴─────────────────┴──────────┴──────┘"
echo ""
echo "3️⃣ 确保 www 子域名配置："
echo "┌──────┬──────┬──────────────────┬──────────┬──────┐"
echo "│ Type │ Name │ Content          │ Proxy    │ TTL  │"
echo "├──────┼──────┼──────────────────┼──────────┼──────┤"
echo "│ CNAME│ www  │ bubblenews.today │ Proxied  │ Auto │"
echo "└──────┴──────┴──────────────────┴──────────┴──────┘"
echo ""
echo "4️⃣ 验证 GitHub Pages 设置："
echo "   - 仓库: DylanDDeng/ai-bubblebrain-daily-news"
echo "   - Settings → Pages → Custom domain: bubblenews.today"
echo ""
echo "5️⃣ 等待 5-10 分钟后运行："
echo "   ./scripts/check-dns.sh"
echo ""
echo "📌 注意：确保使用的是 GitHub Pages 而不是 Cloudflare Pages！"